"""init

Revision ID: 7975fdc10982
Revises: dc7cd538cba7
Create Date: 2025-12-30 10:57:17.347078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7975fdc10982'
down_revision: Union[str, Sequence[str], None] = 'dc7cd538cba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Carts', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Carts', type_='unique')
    # ### end Alembic commands ###
